In [80]:
import pandas as pd
import numpy as np
np.set_printoptions(suppress = True, linewidth=300, precision = 1)

In [56]:
loan_data = np.genfromtxt('loan-data.csv',delimiter=';',skip_header=True, autostrip=True)
loan_data

array([[48010226. ,        nan,    35000. , ...,        nan,        nan,     9453. ],
       [57693261. ,        nan,    30000. , ...,        nan,        nan,     4679.7],
       [59432726. ,        nan,    15000. , ...,        nan,        nan,     1969.8],
       ...,
       [50415990. ,        nan,    10000. , ...,        nan,        nan,     2185.6],
       [46154151. ,        nan,        nan, ...,        nan,        nan,     3199.4],
       [66055249. ,        nan,    10000. , ...,        nan,        nan,      301.9]])

In [30]:
np.isnan(loan_data).sum()

88005

In [57]:
loan_data.shape

(10000, 14)

In [32]:
tmp_fill = np.nanmax(loan_data) + 1
tmp_mean = np.nanmean(loan_data , axis=0)
tmp_mean

C:\Users\dell\AppData\Local\Temp\ipykernel_27592\787100467.py:2: RuntimeWarning: Mean of empty slice
  tmp_mean = np.nanmean(loan_data , axis=0)


array([54015809.2,        nan,    15273.5,        nan,    15311. ,        nan,       16.6,      440.9,        nan,        nan,        nan,        nan,        nan,     3143.9])

In [34]:
tmp_data = np.array([np.nanmin(loan_data , axis = 0), tmp_mean, np.nanmax(loan_data, axis = 0)])
tmp_data

C:\Users\dell\AppData\Local\Temp\ipykernel_27592\38352520.py:1: RuntimeWarning: All-NaN slice encountered
  tmp_data = np.array([np.nanmin(loan_data , axis = 0), tmp_mean, np.nanmax(loan_data, axis = 0)])


array([[  373332. ,        nan,     1000. ,        nan,     1000. ,        nan,        6. ,       31.4,        nan,        nan,        nan,        nan,        nan,        0. ],
       [54015809.2,        nan,    15273.5,        nan,    15311. ,        nan,       16.6,      440.9,        nan,        nan,        nan,        nan,        nan,     3143.9],
       [68616519. ,        nan,    35000. ,        nan,    35000. ,        nan,       29. ,     1373. ,        nan,        nan,        nan,        nan,        nan,    41913.6]])

In [40]:
col_string = np.argwhere(np.isnan(tmp_mean)).squeeze()
col_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [43]:
col_num = np.argwhere(np.isnan(tmp_mean) == False).squeeze()
col_num

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [45]:
loan_data_string = np.genfromtxt('loan-data.csv', delimiter=';', usecols=col_string, skip_header=1, autostrip=True, dtype=str)
loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [51]:
loan_data_num = np.genfromtxt('loan-data.csv', delimiter=';', usecols=col_num, skip_header=1, skip_footer=1,autostrip=True, filling_values = tmp_fill)
loan_data_num

array([[48010226. ,    35000. ,    35000. ,       13.3,     1184.9,     9453. ],
       [57693261. ,    30000. ,    30000. , 68616520. ,      938.6,     4679.7],
       [59432726. ,    15000. ,    15000. , 68616520. ,      494.9,     1969.8],
       ...,
       [45424654. ,    11300. ,    11300. , 68616520. ,      364.6,     3274.9],
       [50415990. ,    10000. ,    10000. , 68616520. , 68616520. ,     2185.6],
       [46154151. , 68616520. ,    10000. ,       16.6,      354.3,     3199.4]])

In [60]:
header_full = np.genfromtxt('loan-data.csv', delimiter=';', skip_footer=loan_data.shape[0], autostrip=True, dtype=str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

In [62]:
header_strings, header_numeric = header_full[col_string] , header_full[col_num]
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [63]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [66]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [76]:
np.unique(loan_data_string[:,2])
month_num = np.chararray.strip(loan_data_string[:,2]," months")
np.unique(month_num)

chararray(['', '36', '60'], dtype='<U69')

In [84]:
df= pd.read_csv("Lending-Company-Total-Price.csv")
df

LoanID StringID    Product CustomerGender    Location    Region  TotalPrice
0       1     id_1  Product B           Male  Location 2  Region 2     16600.0
1       2     id_2  Product B           Male  Location 3       NaN     16600.0
2       3     id_3  Product C         Female  Location 5  Region 5     15600.0
3       4     id_4  Product B           Male  Location 6  Region 1     16600.0
4       5     id_5  Product D         Female  Location 7  Region 2     20250.0

In [85]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9
